# Generated by Django 2.0.2 on 2018-11-15 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_list'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products_list',
            new_name='whiskey',
        ),
    ]
