# Generated by Django 2.0.2 on 2018-11-15 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_beer_rum_vodka_wine'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products_category',
        ),
    ]
